# Generated by Django 5.2.4 on 2025-07-29 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('bank', 'Bank'), ('crypto', 'Crypto'), ('gateway', 'Gateway')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('slug', models.SlugField(unique=True)),
                ('gateway_details', models.CharField(blank=True, help_text='For gateway methods (e.g., PayPal email, CashApp tag, etc.)', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanTypeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('personal', 'Personal Loan'), ('business', 'Business Loan'), ('investment', 'Investment Loan'), ('emergency', 'Emergency Loan')], max_length=20, unique=True)),
                ('interest_rate', models.CharField(default='5.99% APR', max_length=20)),
                ('min_amount', models.PositiveIntegerField(default=0)),
                ('max_amount', models.PositiveIntegerField(default=0)),
                ('term', models.CharField(default='1 - 12 months', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('method', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.depositmethod')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('method', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.depositmethod')),
            ],
        ),
    ]
