# Generated by Django 5.2.4 on 2025-07-29 01:17

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpanel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proof', models.FileField(blank=True, null=True, upload_to='deposit_proofs/')),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('bank_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.bankaccount')),
                ('crypto_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.cryptowallet')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.depositmethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KYCSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', django_countries.fields.CountryField(default='US', max_length=2)),
                ('address_doc_type', models.CharField(max_length=50)),
                ('address_proof', models.FileField(upload_to='kyc/address_proof/')),
                ('id_type', models.CharField(blank=True, max_length=50, null=True)),
                ('id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='kyc/id_document/')),
                ('current_step', models.CharField(choices=[('address', 'Address'), ('identity', 'Identity'), ('review', 'Review'), ('submitted', 'Submitted')], default='address', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('kyc_verified_alert_dismissed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('taxpayer_id', models.CharField(max_length=100)),
                ('employment_status', models.CharField(max_length=100)),
                ('employer_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_source', models.CharField(max_length=100)),
                ('loan_purpose', models.CharField(max_length=100)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_currency', models.CharField(max_length=10)),
                ('loan_term', models.CharField(max_length=50)),
                ('repayment_plan', models.CharField(max_length=50)),
                ('existing_loan', models.BooleanField(default=False)),
                ('collateral_type', models.CharField(max_length=50)),
                ('collateral_amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('wallet_address', models.CharField(max_length=200)),
                ('agree_terms', models.BooleanField(default=False)),
                ('confirm_info_accuracy', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='review', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoginActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('closed', 'Closed')], default='pending', max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('active_loan', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'Pound Sterling')], default='USD', max_length=10)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('next_repayment', models.DateField(blank=True, null=True)),
                ('repayment_alert_pending', models.BooleanField(default=False)),
                ('email_verification_token', models.CharField(blank=True, max_length=64, null=True)),
                ('pending_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('twofa_alert_dismissed_until', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(default='English (United States)', max_length=30)),
                ('timezone', models.CharField(default='(GMT-06:00) Central America', max_length=50)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
